title = "Hugo Test"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "m10c"
paginate = 9
themesDir = "./themes"

[params]
  author = "Kareem"
  description = "Playing around with Hugo settings. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  [[params.social]]
    name = "github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"